SI-8707 Manual Di без Dagger
apatia02/fragment_manager pull request #3
Opened 2024-04-15 12:23 UTC by apatia02

### Что было сделано

Добавлены три компонента (`AppComponent`, `ActivityComponent`,  `FragmentComponent`), для скопов приложения, активити и фрагмента соответственно. В `AppComponent` можно получить доступ к `ImageRepository`, который получает ресурс картинки, в `ActivityComponent` можно получить навигатор, в `FragmentComponent` можно получить доступ к `ClickCounter`, который считает количество нажатий на экран. В нижних скоупах есть доступ к содержанию скоупов родителей, наоборот - нет.

### На что стоит обратить внимание
на пакет di

2024-04-16 08:22 UTC, InVyrsa requested changes

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/FunnyFragment.kt
> +        imageRepository = fragmentComponent.activityComponent.appComponent.imageRepository
Обрати внимание, что в конфигураторах мы инжектим все поля внутри метода inject самой компоненты
<img width="687" alt="image" src="https://github.com/apatia02/fragment_manager/assets/113341960/3b17dadd-aed6-4cf9-95d0-758f44277ce9">

А если залезть в даггер, то можно увидеть, что для активити происходит точно так же
<img width="808" alt="image" src="https://github.com/apatia02/fragment_manager/assets/113341960/52c5b06f-16c0-45bd-a54d-535247c3a891">

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/FunnyFragment.kt
> +        (activity as ActivityManual).activityComponent.injectFragmentComponent(this)
Похоже, что это будет общим для всех фрагментов, поэтому можем прописать в FragmentManual, а потом вызывать `super.onViewCreated(view, savedInstanceState)`

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/FunnyFragment.kt
> +        init()
**Можно не менять**
`init()` тоже можем в базовый класс перенести и сделать `protected open fun`, чтобы вообще `onViewCreated()` тут не вызывать

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/FunnyFragment.kt
> +        (activity as ActivityManual).activityComponent.injectFragmentComponent(this)
Аналогично нужно поправить и для остальных экранчиков

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/activity/MainActivity.kt
> +        activityComponent.setTabFragmentNavigator(this, TAB_1_ID, R.id.fragment_container)
Компонента нам нужна не для того, чтобы в неё лезть и вызывать какие-то методы в данном случае навигатора
Мы из компоненты наш навигатор вытаскиваем, а потом с ним уже работаем
То есть зависимость инжектим с помощью компоненты. Это же у нас DI, а не просто класс-хранилище

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/activity/MainActivity.kt
> +    override lateinit var activityComponent: ActivityComponent
Аналогично, как и во фрагментах можем заинжектить всё, что нам нужно, и спрятать компоненту в базовом классе как приватную переменную

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/features/ClickCounter.kt
> +        fragmentManual.view?.setOnTouchListener { _, _ ->
Каунтер нарушил Single responsibility
Он должен только считать, а тут ещё и лиснер навешивает

2024-04-16 08:22 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/di/ActivityComponent.kt
> +    private val fragmentComponent = FragmentComponent(this)
Зачем нам в активити компоненте фрагмент компонента?
Если посмотреть в наши конфигуратор и в даггер залезть, то там такого нет, а наоборот активити компонента лежит в фрагмент компоненте

2024-04-16 08:23 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/FunnyFragment.kt
> +        imageRepository = fragmentComponent.activityComponent.appComponent.imageRepository
В идеале тебе бы надо привести к такому же виду, как ты переписывал в стайерском курсе. Только там у тебя не было самочинных компонент и ты использовал даггерские, а теперь они появились

2024-04-19 08:37 UTC, InVyrsa requested changes

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/Tab1Fragment.kt
> +        this@Tab1Fragment.view?.setOnTouchListener { _, _ ->
binding.root например тут не подойдёт?

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/Tab1Fragment.kt
> +        activityManual.tabFragmentNavigator?.replace(funnyFragment)
У нас и так есть доступ к Активити из фрагмента и лучше не хранить вторую ссылку, чтобы потом путаницы не было.
Самое простое решение - запровайдить просто навигатор во фрагмент (так как раз и делается у нас на mvp биндингах например)

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/Tab1Fragment.kt
> +        activityManual.tabFragmentNavigator?.replace(funnyFragment)
Аналогично и в других фрагментах надо поправить

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/fragments/FunnyFragment.kt
> +        val imageRepository = activityManual.activityComponent.appComponent.imageRepository
Забыли заинжектить
Вообще это у нас попадает в презентер, конечно, но тут для простоты можем так же инжектить во вью, как и делали

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/di/ActivityComponent.kt
> +    private lateinit var activityManual: ActivityManual
Ссылка на Активити нам тут не нужна
Заинжектить поля мы можем в функции inject() сразу и не придётся хранить ссылку всё время (Так и делалось в компоненте, которую ты переписывал с даггера на manual di)

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/abstractions/ActivityManual.kt
> +    var tabFragmentNavigator: TabFragmentNavigator? = null
Компоненту можем спрятать в базовом классе, сделав приватной

А вот навигатор давай в наследника заинжектим для наглядности

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/abstractions/ActivityManual.kt
> +    fun initTabFragmentNavigator(
Это уже не поставление зависимостей. Ты во вью создал класс просто, а должен был заинжектить уже готовый экземпляр

P.s.
По хорошему навигатор вообще должен был создаться в ActivityModule, который мы в Даггере обозначаем аннотацией `@Module`, но раз уж делать так все же не стали, то надо это хотя бы в компоненте сделать

2024-04-19 08:37 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/abstractions/FragmentManual.kt
> +    lateinit var clickCounter: ClickCounter
Каунтер в общем классе нам точно не нужен
Используется он только на Fragment1, поэтому только туда и должен быть поставлен

2024-04-19 15:04 UTC, apatia02 commented on app/src/main/java/com/example/fragment_manager/presentation/abstractions/ActivityManual.kt
> +    var tabFragmentNavigator: TabFragmentNavigator? = null
не смог заприватить активити компонент, так как он мне нужен для создания фрагмент компонента во фрагменте, пока придумал получать его только через активити.

2024-04-22 10:05 UTC, InVyrsa approved these changes
Конфигуратор добавили только в первом коммите, а в следующих уже нет. Стоит обращать внимание на сообщения комитов, потому что на проекте это может быть важно при поиске импакта от каких-то доработок

Ситуация:
1. Пришел баг, который может быть потенциальным импактом от другой команды разработки
2. Для определения, является ли это импактом от другой команды придётся залезть в историю коммитов и искать нужные изменения

С хорошими сообщениями в коммитах найти нужные изменения гораздо проще - не придётся открывать каждый и искать во всех изменённых файлах.
Аналогично и просто при исправлении бага сокращается время при поиске проблемного участка кода

<img width="695" alt="image" src="https://github.com/apatia02/fragment_manager/assets/113341960/e2a08bec-9048-4c8d-84b4-acf07affcb15">

P.s.
Бывает, что случайно не то в комментарии написал и запушил. Для изменения комментариев можно использовать Force push, чтобы перезаписать сообщение и не плодить новые коммиты

2024-04-22 10:05 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/activity/MainActivityConfigurator.kt
> +        val activity = activityManual as MainActivity
Можно убрать проверку as, если generic использовать, но и так тоже пойдёт

2024-04-22 10:05 UTC, InVyrsa commented on app/src/main/java/com/example/fragment_manager/presentation/abstractions/ActivityManualConfigurator.kt
> +interface ActivityManualConfigurator {
Добавить конфигуратор было хорошим решением. С ними гораздо чище и более читаемо стало

2024-04-22 16:00 UTC, merged